[package]
name = "netdog-wicked"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }